defaultBrowser: chrome
defaultEnvironment: test

browser:
  screenshots: true
  headless: true
  webElement:
    timeout: 10
  environment: int
#  environment: test
#  name: firefox

environment:
    test:
      envName: test
      title: TesterSii
      appUrl: http://146.59.32.4/
    int:
      envName: int
      title: TesterSii
      appUrl: http://146.59.32.4/

urls:
  base: /index.php
